import { describe, expect, it, vi } from "vitest";
import type { GatewayEventFrame } from "./gateway.ts";
import { handleGatewayEvent, type GatewayHost } from "./app-gateway.ts";

function buildHost(overrides?: Partial<GatewayHost>): GatewayHost {
  const runHost = {
    chatRunId: null as string | null,
    chatStream: null as string | null,
    chatStreamStartedAt: null as number | null,
    chatTaskPlan: null as unknown,
  };

  const base = {
    settings: {
      gatewayUrl: "",
      token: "",
      sessionKey: "session-main",
      lastActiveSessionKey: "session-main",
      theme: "system",
      chatFocusMode: false,
      chatShowThinking: true,
      splitRatio: 0.6,
      navCollapsed: false,
      navGroupsCollapsed: {},
      ttsVoice: "",
      ttsInstruct: "",
      ttsLanguage: "",
    },
    password: "",
    client: null,
    connected: true,
    hello: null,
    lastError: null,
    eventLogBuffer: [] as Array<{ ts: number; event: string; payload: unknown }>,
    eventLog: [] as Array<{ ts: number; event: string; payload: unknown }>,
    tab: "chat",
    presenceEntries: [],
    presenceError: null,
    presenceStatus: null,
    agentsLoading: false,
    agentsList: null,
    agentsError: null,
    debugHealth: null,
    assistantName: "Jarvis",
    assistantAvatar: null,
    assistantAgentId: null,
    sessionKey: "session-main",
    getSessionRunHost: () => runHost,
    resetAllSessionRunState: () => undefined,
    chatRunId: null,
    chatThreadsQuery: "",
    chatThreadsLoading: false,
    chatThreadsResult: null,
    chatThreadsError: null,
    subagentMonitorLoading: false,
    subagentMonitorResult: null,
    subagentMonitorError: null,
    execApprovalQueue: [],
    execApprovalError: null,
    theme: "system",
    themeResolved: "dark",
    applySessionKey: "session-main",
    chatHasAutoScrolled: false,
    logsAtBottom: false,
    eventLogBufferRaw: [] as unknown[],
    basePath: "",
    agentsPanel: "overview",
    themeMedia: null,
    themeMediaHandler: null,
    nodesPollInterval: null,
    logsPollInterval: null,
    debugPollInterval: null,
    chatMessage: "",
    chatAttachments: [],
    chatQueue: [],
    chatSending: false,
    chatAvatarUrl: null,
    resetToolStream: () => undefined,
    channelsLoading: false,
    channelsSnapshot: null,
    channelsError: null,
    channelsLastSuccess: null,
    whatsappLoginMessage: null,
    whatsappLoginQrDataUrl: null,
    whatsappLoginConnected: null,
    whatsappBusy: false,
    configLoading: false,
    configRaw: "",
    configRawOriginal: "",
    configValid: null,
    configIssues: [],
    configSaving: false,
    configApplying: false,
    updateRunning: false,
    configSnapshot: null,
    configSchema: null,
    configSchemaVersion: null,
    configSchemaLoading: false,
    configUiHints: {},
    configForm: null,
    configFormOriginal: null,
    configFormDirty: false,
    configFormMode: "raw",
    configSearchQuery: "",
    configActiveSection: null,
    configActiveSubsection: null,
    cronLoading: false,
    cronJobs: [],
    cronStatus: null,
    cronError: null,
    cronForm: {
      name: "",
      description: "",
      enabled: true,
      scheduleKind: "at",
      scheduleAt: "",
      everyAmount: "",
      everyUnit: "minutes",
      cronExpr: "",
      cronTz: "",
      payloadKind: "systemEvent",
      payloadText: "",
      timeoutSeconds: "",
      sessionTarget: "main",
      wakeMode: "next-heartbeat",
      deliveryMode: "announce",
      deliveryChannel: "",
      deliveryTo: "",
      agentId: "",
    },
    cronRunsJobId: null,
    cronRuns: [],
    cronBusy: false,
    debugLoading: false,
    debugStatus: null,
    debugModels: [],
    debugHeartbeat: null,
    debugCallMethod: "",
    debugCallParams: "",
    debugCallResult: null,
    debugCallError: null,
    devicesLoading: false,
    devicesError: null,
    devicesList: null,
    execApprovalsLoading: false,
    execApprovalsSaving: false,
    execApprovalsDirty: false,
    execApprovalsSnapshot: null,
    execApprovalsForm: null,
    execApprovalsSelectedAgent: null,
    logsLoading: false,
    logsError: null,
    logsCursor: null,
    logsFile: null,
    logsEntries: [],
    logsTruncated: false,
    logsLastFetchAt: null,
    logsLimit: 500,
    logsMaxBytes: 200000,
    nodesLoading: false,
    nodes: [],
    presenceLoading: false,
    sessionsLoading: false,
    sessionsResult: null,
    sessionsError: null,
    sessionsFilterActive: "",
    sessionsFilterLimit: "",
    sessionsIncludeGlobal: false,
    sessionsIncludeUnknown: false,
    skillsLoading: false,
    skillsReport: null,
    skillsError: null,
    skillsBusyKey: null,
    skillEdits: {},
    skillMessages: {},
    chatLoading: false,
    chatMessages: [],
    chatThinkingLevel: null,
    chatStream: null,
    chatStreamStartedAt: null,
    chatTaskPlan: null,
    handleOrchestratorAgentEvent: undefined,
    handleOrchestratorStoreEvent: undefined,
    handleChatThreadFinalEvent: undefined,
  };

  return { ...base, ...overrides } as unknown as GatewayHost;
}

describe("app-gateway event contracts", () => {
  it("routes orchestrator events to store handler", () => {
    const handleOrchestratorStoreEvent = vi.fn();
    const host = buildHost({ handleOrchestratorStoreEvent });
    const evt: GatewayEventFrame = {
      type: "event",
      event: "orchestrator",
      payload: { scopeKey: "root-a", hash: "h1", state: { version: 1, boards: [] } },
    };

    handleGatewayEvent(host, evt);
    expect(handleOrchestratorStoreEvent).toHaveBeenCalledTimes(1);
  });

  it("handles final chat events with explicit session keys", () => {
    const handleChatThreadFinalEvent = vi.fn();
    const host = buildHost({
      sessionKey: "session-main",
      settings: {
        ...buildHost().settings,
        lastActiveSessionKey: "session-side",
      },
      handleChatThreadFinalEvent,
    });

    const evt: GatewayEventFrame = {
      type: "event",
      event: "chat",
      payload: {
        runId: "run-1",
        sessionKey: "session-side",
        state: "final",
        message: { role: "assistant", content: [{ type: "text", text: "done" }] },
      },
    };

    handleGatewayEvent(host, evt);
    expect(handleChatThreadFinalEvent).toHaveBeenCalledWith("session-side");
  });
});
